# Generated by Django 3.2 on 2022-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.IntegerField(max_length=14),
        ),
    ]
