# Generated by Django 3.2 on 2022-12-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_passport_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.IntegerField(),
        ),
    ]
