# Generated by Django 3.2 on 2022-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_workproject_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workproject',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='employee.Membership', to='employee.Employee'),
        ),
    ]
